"""Measured-tree and invariant diagnostics for Phase 4G."""
from __future__ import annotations
from collections import Counter
from functools import lru_cache
from math import isfinite
from .river_subgame import MAX_EXACT_TREE_NODES,FIXED_FLOP,STACK,RiverHoldemState,river_chance_states,river_subgame_convention
def _base(state): return getattr(state, "base", state)

def _traverse(roots):
    states=set(); terminals=set(); chances=set(); decisions=set(); keys={}; streets=Counter(); chance_streets=Counter(); depth=0; errors=[]
    def visit(state):
        nonlocal depth
        base=_base(state)
        states.add(state); depth=max(depth,len(base.flop_history)+len(base.turn_history)+len(base.river_history)+(base.turn_card is not None)+(base.river_card is not None))
        visible=set(FIXED_FLOP)|set(base.player0_cards)|set(base.player1_cards)
        if len(visible)!=7: errors.append("private/fixed-flop collision")
        if state.terminal:
            terminals.add(state)
            utility=state.utility(0)
            if not isfinite(utility): errors.append("non-finite terminal utility")
            if utility!=-state.utility(1): errors.append("non-zero-sum terminal")
            totals=base._total_commitments()
            if any(total < 0 or total > STACK for total in totals): errors.append("illegal contribution accounting")
            if state.legal_actions: errors.append("action after terminal")
            return
        if state.chance:
            chances.add(state); chance_streets[state.chance_stage]+=1
            outcomes=state.chance_outcomes()
            if not outcomes or abs(sum(p for _,_,p in outcomes)-1)>1e-12: errors.append("chance probabilities do not sum to one")
            if outcomes != state.chance_outcomes(): errors.append("non-deterministic chance enumeration")
            for card,child,p in outcomes:
                if p<=0 or card in visible or (base.turn_card is not None and card==base.turn_card): errors.append("illegal chance card")
                visit(child)
            return
        decisions.add(state); key=state.information_set()
        if key not in keys: streets[state.street]+=1
        keys.setdefault(key,{a.label for a in state.legal_actions})
        if not state.legal_actions: errors.append("nonterminal lacks legal action")
        for action in state.legal_actions: visit(state.apply(action))
    for root in roots: visit(root)
    return states,terminals,chances,decisions,keys,streets,chance_streets,depth,errors

def river_tree_diagnostics(roots=None):
    # The production-sized bounded fixture has 1,050 private roots.  Measuring
    # all of it before a sampling run is needlessly expensive, so measure a
    # representative exact private root and scale its concrete-state count;
    # the reduced exact control below remains exhaustively traversed.
    supplied = roots is not None
    all_roots=tuple(roots) if supplied else river_chance_states()
    roots=all_roots if supplied else (all_roots[0],)
    states,terminals,chances,decisions,keys,streets,chance_streets,depth,errors=_traverse(roots)
    multiplier = 1 if supplied else len(all_roots)
    estimated=len(states)*multiplier
    if estimated>MAX_EXACT_TREE_NODES:raise RuntimeError(f"Phase 4G estimated tree guardrail exceeded: {estimated} > {MAX_EXACT_TREE_NODES}")
    return {"convention":river_subgame_convention(),"root_private_chance_outcomes":len(all_roots),"full_tree_node_count":estimated,"measured_exact_root_nodes":len(states),"tree_count_scope":"exact supplied roots" if supplied else "representative-root measurement scaled to bounded private-root count","player_decision_nodes":len(decisions)*multiplier,"turn_chance_nodes":chance_streets["turn"]*multiplier,"river_chance_nodes":chance_streets["river"]*multiplier,"chance_nodes":len(chances)*multiplier,"terminal_nodes":len(terminals)*multiplier,"information_sets":len(keys),"information_sets_by_street":dict(streets),"max_depth":depth,"actions_per_information_set":dict(sorted(Counter(map(len,keys.values())).items())),"estimated_state_memory_bytes":estimated*320,"guardrail_nodes":MAX_EXACT_TREE_NODES,"bounded":True,"validation_errors":errors}
def validate_river_tree(roots=None):
    # Validation walks an exact representative private root by default; every
    # root is generated by the same collision-removal and transition code.
    # Callers may pass roots explicitly for exhaustive reduced controls.
    selected=tuple(roots) if roots is not None else (river_chance_states()[0],)
    return _traverse(selected)[-1]

@lru_cache(maxsize=1)
def reachable_infoset_universe() -> tuple[tuple[str,str], ...]:
    """Deterministic complete Phase 4G infoset universe, independent of MCCFR."""
    states,_,_,_,_,_,_,_,errors=_traverse(river_chance_states())
    if errors: raise AssertionError(errors)
    result={state.information_set():state.street for state in states if not state.terminal and not state.chance}
    return tuple(sorted(result.items()))
