import { useState } from "react";
import type { HandHistory, HistoryEvent, HistoryPlayer, ValidationSummary } from "./types";

const player = (value: HistoryPlayer | null) => value === "a" ? "Bot A" : value === "b" ? "Bot B" : "-";
const text = (event: HistoryEvent) => event.event_type.replaceAll("_", " ");
const hidden = new Set(["deck", "deck_order", "remaining_deck", "burn_cards", "final_board"]);
export default function ReplayEvent({ history, validation }: { history: HandHistory; validation?: ValidationSummary }) {
  const [index, setIndex] = useState(0); const move = (next: number) => setIndex(Math.max(0, Math.min(next, history.events.length - 1))); const event = history.events[index];
  if (!event) return null;
  return <section className="replay-event"><div className="metrics"><div><span>Hand ID</span><strong>{history.hand_id}</strong></div><div><span>Schema</span><strong>{history.history_schema_version}</strong></div><div><span>Seed</span><strong>{history.hand_seed ?? "-"}</strong></div><div><span>Final stacks</span><strong>{history.final_stack_a ?? "-"} / {history.final_stack_b ?? "-"}</strong></div><div><span>Winner</span><strong>{history.winner === "a" ? "Bot A" : history.winner === "b" ? "Bot B" : history.winner ?? "-"}</strong></div><div><span>Ending</span><strong>{history.ending_type ?? "-"}</strong></div><div><span>Events</span><strong>{history.events.length}</strong></div></div>{validation?.valid === false && <p className="error">Validation failed: {validation.errors.join("; ")}</p>}<div className="replay-controls"><button type="button" onClick={() => move(0)} disabled={index === 0}>First event</button><button type="button" onClick={() => move(index - 1)} disabled={index === 0}>Previous event</button><span>Event {index + 1} of {history.events.length}</span><input aria-label="Event index" type="number" min={0} max={history.events.length - 1} value={index} onChange={(e) => move(Number(e.target.value))} /><button type="button" onClick={() => move(index + 1)} disabled={index === history.events.length - 1}>Next event</button><button type="button" onClick={() => move(history.events.length - 1)} disabled={index === history.events.length - 1}>Last event</button></div><div className="replay-columns"><section className="event-state"><h2>Table state</h2><p>Street: {event.street} | Pot: {event.pot_after} | Acting: {player((event.acting_player_after as HistoryPlayer | null) ?? event.actor)}</p><div className="board">{event.board.length ? event.board.map((card) => <span className="card-token" key={card}>{card}</span>) : <span className="muted">No public cards yet</span>}</div><p>Bot A stack {event.stack_a_after} | Bot B stack {event.stack_b_after} | Highest bet {event.current_highest_bet_after}</p><p>Commitments A/B: {event.street_commitment_a_after} / {event.street_commitment_b_after}</p><h2>Event {event.event_index}: {text(event)}</h2><div className="detail-list">{Object.entries(event).filter(([key, value]) => !hidden.has(key) && value !== null && value !== undefined && value !== "").map(([key, value]) => <div key={key}><span>{key.replaceAll("_", " ")}</span><strong>{typeof value === "object" ? JSON.stringify(value) : String(value)}</strong></div>)}</div></section><section className="timeline"><h2>Timeline</h2>{history.events.map((item) => <button type="button" key={item.event_index} className={item.event_index === index ? "selected-event" : ""} onClick={() => move(item.event_index)}>{item.event_index} | {text(item)} | {item.street}<small>{item.actor ? `${player(item.actor)}: ` : ""}{text(item)}</small></button>)}</section></div></section>;
}
