import { FormEvent, useState } from "react";
import type { BotName, HandHistory, HandHistoryRequest, HandHistoryResponse, HistoryEvent, HistoryPlayer } from "./types";

type FormState = { bot_a: BotName; bot_b: BotName; starting_stack_a: string; starting_stack_b: string; small_blind: string; big_blind: string; button_player: HistoryPlayer; seed: string; equity_iterations: 500 | 1000 | 2000 };
const DEFAULTS: FormState = { bot_a: "random", bot_b: "random", starting_stack_a: "10000", starting_stack_b: "10000", small_blind: "50", big_blind: "100", button_player: "a", seed: "0", equity_iterations: 1000 };
const BOTS: BotName[] = ["random", "tight", "aggressive", "equity"];
const player = (p: HistoryPlayer | null) => p === "a" ? "Bot A" : p === "b" ? "Bot B" : "-";
const integer = (s: string, label: string) => { if (!s.trim()) throw new Error(`${label} is required.`); if (!/^-?\d+$/.test(s.trim())) throw new Error(`${label} must be a whole number.`); return Number(s); };
const eventText = (e: HistoryEvent) => e.event_type.replaceAll("_", " ");

export default function Replay() {
  const [form, setForm] = useState<FormState>(DEFAULTS); const [result, setResult] = useState<HandHistoryResponse | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [index, setIndex] = useState(0);
  const history: HandHistory | undefined = result?.history; const event = history?.events[index];
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((old) => ({ ...old, [key]: value }));
  const move = (next: number) => setIndex(Math.max(0, Math.min(next, (history?.events.length ?? 1) - 1)));
  async function submit(e: FormEvent) { e.preventDefault(); if (loading) return; setError(""); try { const a = integer(form.starting_stack_a, "Starting stack A"); const b = integer(form.starting_stack_b, "Starting stack B"); const sb = integer(form.small_blind, "Small blind"); const bb = integer(form.big_blind, "Big blind"); const seed = integer(form.seed, "Seed"); if (a <= 0 || b <= 0) throw new Error("Both starting stacks must be positive."); if (sb <= 0 || bb <= 0) throw new Error("Blinds must be positive."); if (sb > bb) throw new Error("Small blind cannot exceed the big blind."); const request: HandHistoryRequest = { bot_a: form.bot_a, bot_b: form.bot_b, starting_stack_a: a, starting_stack_b: b, small_blind: sb, big_blind: bb, button_player: form.button_player, seed, equity_iterations: form.equity_iterations }; setLoading(true); const response = await fetch("/api/histories/hand", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(request) }); const body: unknown = await response.json().catch(() => null); if (!response.ok) throw new Error("The replay request was rejected."); setResult(body as HandHistoryResponse); setIndex(0); } catch (err) { setError(err instanceof TypeError ? "The backend is unavailable." : err instanceof Error ? err.message : "Replay failed."); } finally { setLoading(false); } }
  return <section className="panel replay-panel"><h1>Single-Hand Replay</h1><p>Run one deterministic heads-up hand and inspect the recorded engine events step by step.</p><p className="muted">Generated local histories only. No external poker websites. Folded private cards remain hidden. Future board cards appear only at their reveal event.</p>
    <form onSubmit={submit}><div className="form-grid"><label>Bot A<select value={form.bot_a} onChange={(e) => update("bot_a", e.target.value as BotName)}>{BOTS.map((bot) => <option key={bot}>{bot}</option>)}</select></label><label>Bot B<select value={form.bot_b} onChange={(e) => update("bot_b", e.target.value as BotName)}>{BOTS.map((bot) => <option key={bot}>{bot}</option>)}</select></label><label>Starting stack A<input value={form.starting_stack_a} onChange={(e) => update("starting_stack_a", e.target.value)} /></label><label>Starting stack B<input value={form.starting_stack_b} onChange={(e) => update("starting_stack_b", e.target.value)} /></label><label>Small blind<input value={form.small_blind} onChange={(e) => update("small_blind", e.target.value)} /></label><label>Big blind<input value={form.big_blind} onChange={(e) => update("big_blind", e.target.value)} /></label><label>Seed<input value={form.seed} onChange={(e) => update("seed", e.target.value)} /></label><label>Button player<select value={form.button_player} onChange={(e) => update("button_player", e.target.value as HistoryPlayer)}><option value="a">A</option><option value="b">B</option></select></label><label>Equity iterations<select value={form.equity_iterations} onChange={(e) => update("equity_iterations", Number(e.target.value) as FormState["equity_iterations"])}><option value={500}>500</option><option value={1000}>1000</option><option value={2000}>2000</option></select></label></div><button className="analyze" disabled={loading}>{loading ? "Generating replay..." : "Run replay"}</button><span className="sr-status" role="status">{loading ? "Generating replay..." : ""}</span></form>
    {error && <p className="error" role="alert">{error}</p>}{history && <><div className="metrics"><div><span>Hand ID</span><strong>{history.hand_id}</strong></div><div><span>Schema</span><strong>{history.history_schema_version}</strong></div><div><span>Seed</span><strong>{history.hand_seed ?? "-"}</strong></div><div><span>Final stacks</span><strong>{history.final_stack_a ?? "-"} / {history.final_stack_b ?? "-"}</strong></div><div><span>Winner</span><strong>{history.winner ?? "-"}</strong></div><div><span>Ending</span><strong>{history.ending_type ?? "-"}</strong></div><div><span>Board</span><strong>{history.final_board.join(" ") || "No board cards"}</strong></div><div><span>Events</span><strong>{history.events.length}</strong></div></div>{result?.validation.valid === false && <p className="error">Validation failed: {result.validation.errors.join("; ")}</p>}<div className="replay-controls"><button type="button" onClick={() => move(0)} disabled={index === 0}>First event</button><button type="button" onClick={() => move(index - 1)} disabled={index === 0}>Previous event</button><span>Event {index + 1} of {history.events.length}</span><input aria-label="Event index" type="number" min={0} max={history.events.length - 1} value={index} onChange={(e) => move(Number(e.target.value))} /><button type="button" onClick={() => move(index + 1)} disabled={index === history.events.length - 1}>Next event</button><button type="button" onClick={() => move(history.events.length - 1)} disabled={index === history.events.length - 1}>Last event</button></div>{event && <div className="replay-columns"><section className="event-state"><h2>Table state</h2><p>Street: {event.street} | Pot: {event.pot_after} | Acting: {player((event.acting_player_after as HistoryPlayer | null) ?? event.actor)}</p><div className="board">{event.board.length ? event.board.map((card) => <span className="card-token" key={card}>{card}</span>) : <span className="muted">No public cards yet</span>}</div><p>Bot A stack {event.stack_a_after} | Bot B stack {event.stack_b_after} | Highest bet {event.current_highest_bet_after}</p><p>Commitments A/B: {event.street_commitment_a_after} / {event.street_commitment_b_after}</p><h2>Event {event.event_index}: {eventText(event)}</h2><div className="detail-list">{Object.entries(event).filter(([, value]) => value !== null && value !== undefined && value !== "").map(([key, value]) => <div key={key}><span>{key.replaceAll("_", " ")}</span><strong>{typeof value === "object" ? JSON.stringify(value) : String(value)}</strong></div>)}</div></section><section className="timeline"><h2>Timeline</h2>{history.events.map((item) => <button type="button" key={item.event_index} className={item.event_index === index ? "selected-event" : ""} onClick={() => move(item.event_index)}>{item.event_index} | {eventText(item)} | {item.street}<small>{item.actor ? `${player(item.actor)}: ` : ""}{eventText(item)}</small></button>)}</section></div>}</>}</section>;
}
